sls: jury-rigged the shit out of the 7th lab script

diff --git a/sophomore/system-level-software/lab7/script b/sophomore/system-level-software/lab7/script
--- a/sophomore/system-level-software/lab7/script
+++ b/sophomore/system-level-software/lab7/script
@@ -1,14 +1,16 @@
 ERR_PATH="$HOME/lab1_err"
 
-while [ "$menu" != 6 ]
+while [ "$menu" != 8 ]
 do
-    echo '1. Напечатать имя текущего каталога'
-    echo '2. Сменить текущий каталог'
-    echo '3. Выдать список пользователей, имеющих хотя бы один процесс'
-    echo '4. Создать файл'
-    echo '5. Скопировать файл'
-    echo '6. Выйти из программы'
-    echo 'Выберите пункт меню:'
+    echo '1. Print current directory'
+    echo '2. Change current directory'
+    echo '3. Print all users with at least one process'
+    echo '4. Create file'
+    echo '5. Copy file'
+	echo '6. Delete file'
+	echo '7. Change file/directory permissions'
+    echo '8. Exit'
+    echo 'Choose option:'
 
     read menu || break
 
@@ -17,26 +19,74 @@ do
             pwd 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
         ;;
         2)
-            echo 'Введите путь к каталогу:'
-            read path_to_dir
+	    read -p 'Path to directory: ' path_to_dir
             cd "$path_to_dir" 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
         ;;
         3)
             ps -Af | awk '!/pts|UID|console/{ print $1 }' | grep -v "?" | sort | uniq 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
         ;;
         4)
-            echo 'Введите имя файла:'
-            read filename
-			echo ”Введите содержимое файла, а затем нажмите Ctrl+D, чтобы создать файл.\n”
-            cat > "$filename" 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+            read -r -p 'Enter file name: ' filename
+		if [[ $filename == "" ]]
+		then
+			filename=$'\n'
+		fi
+		echo "create $filename (y/n)?"
+           		read confirm
+            		if [ $confirm = "y" ]
+            		then
+            			touch "$filename" 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+			fi
         ;;
         5)
-            echo 'Введите имя файла:'
-            read filename
-echo 'Введите путь для копирования файла:'
-            read new_dir
-            cp "$filename" "$new_dir"  2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2 
-        ;;
+            	read -p 'Enter file name: ' filename
+            	read -p 'Path to copy to: ' new_dir
+		echo "cp: copy $filename to $new_dir (y/n)?"
+           		read confirm
+            		if [ $confirm = "y" ]
+            		then
+
+		if [[ $filename =~ ^/.* ]]
+		then
+				cp "$filename" "$new_dir"  2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+			else
+				cp "./$filename" "$new_dir"  2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+			fi
+		fi
+
+        	;;
+		6)
+			read -p 'Enter filename or path: ' filename
+			if [[ $filename == "" ]]
+			then
+				filename=$'\n'
+			fi
+			echo "rm: remove $filename (y/n)?"
+           		read confirm
+            		if [ $confirm = "y" ]
+            		then
+				if [[ $filename =~ ^/.* ]]
+				then
+					rm "$filename" 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+				else
+					rm "./$filename" 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+				fi
+			fi
+		;;
+		7)
+			read -p 'Enter file/directory name or path: ' filename
+			if [[ $filename == "" ]]
+			then
+				filename=$'\n'
+			fi
+			read -p 'Enter permissions: ' permissions
+			if [[ $filename =~ ^/.* ]]
+			then
+				chmod "$permissions" "$filename" 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+			else
+				chmod "$permissions" "./$filename" 2>>"$ERR_PATH" || echo 'An error has occurred. Check log file.' 1>&2
+			fi
+		;;
     esac
 
 done
